# 03 - Preprocessing and Datasets Split

## Data sources
- **ML-HydPARK** (Zenodo, v0.0.5): cleaned experimental thermodynamic data for metal hydrides (~770 entries)
- **ElementalH_Ef** and **ElementalH_Ef_MP**: elemental features from Materials Project, sourced from HEAhydrideML (Witman et al.)

## Target Variables
- `Temperature_oC`
- `Hydrogen_Weight_Percent`

## Goals
- Handling missing values
- Feature selection and engineering
- Split into Dataset A and Dataset B
- Per-dataset: encoding, scaling and train/val/test split

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Loading the dataset
df = pd.read_csv('../data/processed/ML-HYDPARK_eda_cleaned.csv')
df.shape

(772, 9)

In [3]:
df.head()

,Material_Class,Composition_Formula,Hydrogen_Weight_Percent,Heat_of_Formation_kJperMolH2,Temperature_oC,Pressure_Atmospheres_Absolute,Entropy_of_Formation_JperMolH2perK,LnEquilibrium_Pressure_25C,HtoM
0,A2B,Th2Al,0.8,130.0,500.0,0.001,110.711134,-39.127349,1.309571
1,A2B,Ti2Cu,2.2,130.0,500.0,0.120,150.515102,-34.339857,1.184850
2,A2B,Zr2Cu,1.3,144.0,600.0,0.003,116.621978,-44.064155,1.071443
3,A2B,Zr2Ni,1.3,183.0,604.0,0.003,160.332084,-54.539843,1.050307
4,A2B,Mg2Ni,3.6,64.5,299.0,3.200,122.403296,-11.297687,1.325126

## Dropping of features

`LnEquilibrium_Pressure_25C`: it is redundant as it can be calculated from `Heat_of_Formation_kJperMolH2` and `Entropy_of_Formation_JperMolH2perK` via the van 't Hoff equation.

`HtoM`: it is mathematically derivable from `Hydrogen_Weight_Percent`, so keeping both when one is the target variable would introduce data leakage.

In [4]:
# Dropping 'LnEquilibrium_Pressure_25C'
df = df.drop(columns = ['LnEquilibrium_Pressure_25C'], axis = 1)
df.shape

(772, 8)

In [5]:
# Dropping 'HtoM'
df = df.drop(columns = ['HtoM'], axis = 1)
df.shape

(772, 7)

In [6]:
df.head()

,Material_Class,Composition_Formula,Hydrogen_Weight_Percent,Heat_of_Formation_kJperMolH2,Temperature_oC,Pressure_Atmospheres_Absolute,Entropy_of_Formation_JperMolH2perK
0,A2B,Th2Al,0.8,130.0,500.0,0.001,110.711134
1,A2B,Ti2Cu,2.2,130.0,500.0,0.120,150.515102
2,A2B,Zr2Cu,1.3,144.0,600.0,0.003,116.621978
3,A2B,Zr2Ni,1.3,183.0,604.0,0.003,160.332084
4,A2B,Mg2Ni,3.6,64.5,299.0,3.200,122.403296